fernetKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=
webserverSecretKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=
executor: KubernetesExecutor

dags:
  gitSync:
    enabled: true
    repo: https://github.com/rgualter/KubernetesforDataEngineering.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"