fernetKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=
webserverSecretKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/rgualter/KubernetesforDataEngineering.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"

  #persistence:
  #  # Enable persistent volume for storing logs
  #  enabled: true
  #  # Volume size for logs
  #  size: 10Gi
  #  # Annotations for the logs PVC
  #  annotations: {}
  #  # If using a custom storageClass, pass name here
  #  storageClassName:
  #  ## the name of an existing PVC to use
  #  existingClaim: